### ISSUE TITLE
data prop causing Uncaught TypeError: Cannot read properties of undefined (reading 'matrix_values')

### ISSUE THREAD

**Issue by donikaSkenderbeut** [bronz3beard/react-matrix#3]
Hello, 

I'm using the data object from your examples and passing it as shown in the example on GitHub however I get Uncaught TypeError: Cannot read properties of undefined (reading 'matrix_values'). Looks like the data prop is undefined at the point when it's being accessed within the component.

**Comment by bronz3beard** [comment]
hi [donikaSkenderbeut](https://github.com/donikaSkenderbeut) I am very sorry for the delay, this notification was lost amongst all others!!

I have a working demo that uses the same code the only difference I can think of right now is your data Vs the mock data I use in the demo.
Take a look at this file to see if there are any clues for your solution.

it could be that I have documented how to use this dependency poorly and I will update the docs, if ti is with the code I will fix that issue, and I will also look at providing better feedback on general errors beyond a TypeError.

Thanks for letting me know, I will let you know when this is sorted 👍

mock data from demo: `https://github.com/bronz3beard/react-matrix/blob/main/src/lib/utils/data.js`

**Comment by bronz3beard** [comment]
This should be resolved now, please let me know if you have any other issues [donikaSkenderbeut](https://github.com/donikaSkenderbeut) and thanks again for letting me know about the bug, I really appreciate it! 🙌
